/// Flutter icons Emotions
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Emotions
///      fonts:
///       - asset: fonts/Emotions.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Emotions {
  Emotions._();

  static const _kFontFam = 'Emotions';
  static const String? _kFontPkg = null;

  static const IconData like = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
